---
- name: 'Provision remote-builder'
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - { role: andrewrothstein.terraform, terraform_ver: 0.14.11 }
    - { role: andrewrothstein.kubectl, kubectl_ver: v1.20.6 }
    - { role: andrewrothstein.kustomize, kustomize_ver: v4.1.2 }