---
- name: 'Provision remote-builder'
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - { role: diodonfrost.terraform, terraform_version: 0.14.11 }
    - { role: andrewrothstein.kubectl, kubectl_ver: v1.20.6 }
    - { role: andrewrothstein.kustomize, kustomize_ver: v4.1.2 }