steps:
   - id: 'build remote-builder'
     name: 'gcr.io/cloud-builders/docker'
     args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/remote-builder', '.' ]
images: ['eu.gcr.io/$PROJECT_ID/remote-builder']
timeout: 900s